# please create .env file in current directory and set hostname
@hostname={{$dotenv HOSTNAME}}
@scheme={{$dotenv SCHEME}}

### 

# @prompt password
GET {{scheme}}://{{hostname}}/{{api-endpoint}}/people/{{user}}/preferences
Content-Type: {{contentType}}
Authorization: Basic {{user}}:{{password}}

### 

# @prompt password
POST {{scheme}}://{{hostname}}/share/page/dologin
Content-Type: application/x-www-form-urlencoded

username={{user}}&password={{password}}

###

POST {{scheme}}://{{hostname}}/share/proxy/alfresco/api/people/admin/preferences
Content-Type: {{contentType}} 

{
    "org": {
        "alfresco": {
            "share": {
                "documentList": {
                    "sortAscending": false,
                    "viewRendererName": "simple"
                }
            }
        }
    }
}

### get all renditions per node

@nodeId=cc869d71-fe10-42e7-869d-71fe10b2e7a5
@versionId=1.2

# @prompt password
GET {{scheme}}://{{hostname}}/{{api-endpoint}}/nodes/{{nodeId}}/renditions
Content-Type: {{contentType}}
Authorization: Basic {{user}}:{{password}}

### get all renditions per node with given version 

# @prompt password
GET {{scheme}}://{{hostname}}/{{api-endpoint}}/nodes/{{nodeId}}/versions/{{versionId}}/renditions
Content-Type: {{contentType}}
Authorization: Basic {{user}}:{{password}}

### create pdf rendition for node with given version 

@renditionId = pdf

# @prompt password
POST {{scheme}}://{{hostname}}/{{api-endpoint}}/nodes/{{nodeId}}/versions/{{versionId}}/renditions
Content-Type: {{contentType}}
Authorization: Basic {{user}}:{{password}}

{
    "id": "{{renditionId}}"
}

### get rendition information for specific file

# @prompt password
#
GET {{scheme}}://{{hostname}}/{{api-endpoint}}/nodes/{{nodeId}}/versions/{{versionId}}/renditions/{{renditionId}}
Content-Type: {{contentType}}
Authorization: Basic {{user}}:{{password}}

### delete rendition with version and file

# @prompt password
DELETE {{scheme}}://{{hostname}}/{{api-endpoint}}/nodes/{{nodeId}}/versions/{{versionId}}/renditions/{{renditionId}}
Content-Type: {{contentType}}
Authorization: Basic {{user}}:{{password}}
